//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miPrimerMVCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos1
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> IsRowCreatedat { get; set; }
        public Nullable<System.DateTime> IsRowUdDated { get; set; }
    }
}
