//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web100.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamenEntitiesPersona : DbContext
    {
        public ExamenEntitiesPersona()
            : base("name=ExamenEntitiesPersona")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> Persona { get; set; }

        public System.Data.Entity.DbSet<Web100.Models.ViewModel.RegistroPersona> RegistroPersonas { get; set; }

        public System.Data.Entity.DbSet<Web100.Models.ViewModel.ListaPersona> ListaPersonas { get; set; }
    }
}
