//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miPrimerMVCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas
    {
        public int id { get; set; }
        public string nombres { get; set; }
        public string apellidop { get; set; }
        public string apellidom { get; set; }
        public Nullable<int> edad { get; set; }
        public string sexo { get; set; }
    }
}
